### ISSUE TITLE
[BUG] 500 internal server Error

### ISSUE THREAD

**Issue by Dylan-Blanchard** [sailpoint-oss/isc-community-toolbox#22]
**Describe the bug**
I can't login to the toolbox I'm getting a 500 with the message "No Response From IDN"

I went through the developper tools and the first access calls go to 302 or 303 but the callback returns a 500. 
I've also tried using a private navigation in localhost:3000. It does ask me for authentication, which then works if I open another tab from this navigation to my IDN tenant.  

**Screenshots**
![image](https://github.com/sailpoint-oss/isc-community-toolbox/assets/162340202/8dd36cbc-834c-4f46-980f-1996ff0905e7)

**Operating System (please complete the following information):**
 - OS: Windows 10 19045.4170

I'm available for more test if needed.

**Comment by gakiris** [comment]
I am also having the same issue with Macbook Pro M1 14.6.1

**Comment by rahulkspzr** [comment]
I am facing the same issue Windows 11.

**Comment by kevin-gorton-sp** [comment]
Here is what is happening. from the logs.

`10:36:51.481 > Hello, log!
10:36:51.588 > Creating window...
[42632:0319/103652.478:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
Handle Session: undefined
Load runnning for path /
locals { session: undefined, idnSession: undefined }
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
(node:20940) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Handle Session: undefined
session {
  baseUrl: 'https://ps-jwoolsey.api.identitynow.com',
  tenantUrl: 'https://ps-jwoolsey.identitynow.com'
}
Handle Session: {
  baseUrl: 'https://ps-jwoolsey.api.identitynow.com',
  tenantUrl: 'https://ps-jwoolsey.identitynow.com'
}
Load runnning for path /callback
Error: Cookie "idnSession" is too large, and will be discarded by the browser
    at set_internal (C:\repo\isc-community-toolbox\node_modules\@sveltejs\kit\src\runtime\server\cookie.js:198:11)
    at Object.set (C:\repo\isc-community-toolbox\node_modules\@sveltejs\kit\src\runtime\server\cookie.js:117:4)
    at Module.setSessionDetails (C:\repo\isc-community-toolbox\src\lib\encryption.ts:38:11)
    at load (C:\repo\isc-community-toolbox\src\routes\callback\+page.server.ts:38:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Module.load_server_data (C:\repo\isc-community-toolbox\node_modules\@sveltejs\kit\src\runtime\server\page\load_data.js:61:17)
    at async eval (C:\repo\isc-community-toolbox\node_modules\@sveltejs\kit\src\runtime\server\page\index.js:140:13)`

I have not been able to track down why it thinks this session is to large.   it looks like sometimes the token the ISC responds with is longer and this is when that occures.
and the callback API is failing on this API callback stating that the cookie is to large

![Image](https://github.com/user-attachments/assets/6998abf0-cbe0-48fb-bc17-7acef674b824)

![Image](https://github.com/user-attachments/assets/5c9030a9-fcc5-47fb-8c8e-689039b0b7f6)

**Comment by developer-relations-sp** [comment]
This issue has been mentioned on **SailPoint Developer Community**. There might be relevant details there:

https://developer.sailpoint.com/discuss/t/isc-community-toolbox/26588/34

**Comment by msahraouii** [comment]
Hello, same for me. The issue persists :

<img width="532" alt="Image" src="https://github.com/user-attachments/assets/63bd95a9-66f8-41e1-8ea9-7dfd7939d197" />

**Comment by rfondrick** [comment]
I am having the same issue listed above.  Is there any update to this yet?

Thanks,
